// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'get-started/index',
      },
      items: [
        'get-started/what-is-sivi',
        'get-started/how-to-use-sivi',
        'get-started/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Brand Kit',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'brand-kit/index',
      },
      items: [
        'brand-kit/brand-setup',
        'brand-kit/brand-colors',
        'brand-kit/brand-fonts',
        'brand-kit/brand-assets-library',
      ],
    },
    {
      type: 'category',
      label: 'Generate Your First Design',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'generate-your-first-design/index',
      },
      items: [
        'generate-your-first-design/prompt-to-design',
        'generate-your-first-design/choose-dimensions',
        'generate-your-first-design/languages',
        'generate-your-first-design/design-assets',
        'generate-your-first-design/marketing-idea',
        'generate-your-first-design/edit-content',
      ],
    },
    {
      type: 'category',
      label: 'Design Generation',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'design-generation/index',
      },
      items: [
        'design-generation/generation-settings',
        'design-generation/design-count',
        'design-generation/design-style',
        'design-generation/download-generated-design',
        'design-generation/view-behind-the-scenes',
        'design-generation/share-designs',
      ],
    },
    {
      type: 'category',
      label: 'Editing Your Design',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'editing-your-design/index',
      },
      items: [
        'editing-your-design/edit-generated-design',
        'editing-your-design/vectors',
        'editing-your-design/fonts',
        'editing-your-design/colors',
        'editing-your-design/enhance',
        'editing-your-design/download-edited-design',
        'editing-your-design/crop-images',
        'editing-your-design/layers',
      ],
    },
    {
      type: 'category',
      label: 'Plans and Credits',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'plans-and-credits/index',
      },
      items: [
        'plans-and-credits/pricing-details',
        'plans-and-credits/credits',
        'plans-and-credits/upgrade-plan',
        'plans-and-credits/downgrade',
        'plans-and-credits/auto-renew',
        'plans-and-credits/cancel-subscription',
      ],
    },
    {
      type: 'category',
      label: 'Account Settings',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'account-settings/index',
      },
      items: [
        'account-settings/profile-details',
        'account-settings/workspace',
        'account-settings/theme',
        'account-settings/delete-account',
        'account-settings/folders',
        'account-settings/view-designs',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting FAQ',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'troubleshooting-faq/index',
      },
      items: [
        'troubleshooting-faq/generation-time',
        'troubleshooting-faq/design-quality',
        'troubleshooting-faq/image-relevance',
        'troubleshooting-faq/color-issues',
        'troubleshooting-faq/generation-failure',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'use-cases/index',
      },
      items: [
        'use-cases/multilingual-ad-campaign',
        'use-cases/one-prompt-for-multiple-platforms',
        'use-cases/list-step-by-step-information',
        'use-cases/promote-event',
        'use-cases/highlight-benefits',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'advanced/index',
      },
      items: [
        'advanced/jobs',
        'advanced/api',
        'advanced/community',
        'advanced/get-in-touch',
      ],
    },
    {
      type: 'category',
      label: 'Working with Content',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'doc',
        id: 'working-with-content/index',
      },
      items: [
        'working-with-content/content-engineering',
        'working-with-content/generate-designs-for-your-content',
        'working-with-content/add-assets',
        'working-with-content/group-blocks',
        'working-with-content/add-heading',
        'working-with-content/adding-colors-and-fonts',
        'working-with-content/add-a-divider',
        'working-with-content/content-blocks',
        'working-with-content/add-buttons',
        'working-with-content/add-contact-and-social',
        'working-with-content/move-blocks',
        'working-with-content/highlight-text',
        'working-with-content/pages',
        'working-with-content/bulleted-list',
        'working-with-content/numbered-list',
        'working-with-content/change-tags',
        'working-with-content/content-snippets',
        'working-with-content/save-content',
        'working-with-content/primary-asset',
        'working-with-content/add-a-coupon',
        'working-with-content/add-date-or-time',
        'working-with-content/add-hashtag',
        'working-with-content/content-score',
        'working-with-content/add-offer',
      ],
    },
  ],
};

export default sidebars;
